const String TERMOS_DE_USO =
    '''Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam pulvinar turpis sit amet lacus facilisis consequat. Integer vel nibh maximus, egestas mi ac, lobortis mi. Aliquam pulvinar turpis non ante facilisis aliquam. Aliquam nec lacinia odio. Maecenas leo tortor, semper quis interdum vel, tristique sit amet sapien. Vivamus egestas vitae nisl ac porta. Phasellus scelerisque lorem non orci porta interdum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur eget lorem ultricies, blandit dui posuere, tempus enim. Aenean luctus augue vel euismod elementum. Donec lacinia vestibulum nibh, quis laoreet eros sodales vitae. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas varius mauris at arcu feugiat, ut mollis lorem accumsan. Cras ultricies at est vel sollicitudin.

Donec id elit sit amet turpis dignissim tempus quis id nisl. Aliquam faucibus ullamcorper enim non interdum. Vivamus vel nisi viverra ante faucibus sagittis nec non neque. Integer in odio vel quam efficitur aliquam ac sit amet massa. Integer non arcu a mauris blandit malesuada eu in orci. In dignissim arcu placerat, molestie ligula ac, rutrum metus. Vivamus venenatis rutrum mi, non varius sapien aliquam a. Donec rutrum scelerisque neque, at pharetra sem vulputate quis.

Ut et velit nec ipsum consectetur finibus a nec tellus. Aliquam vitae neque a metus finibus sollicitudin vel ut magna. Sed ac feugiat urna, viverra mollis ante. Suspendisse cursus tristique urna a sodales. Mauris in eleifend turpis. Aliquam euismod dignissim tempor. Proin fringilla, lacus at sollicitudin mattis, libero mi convallis sapien, in molestie arcu lectus eget arcu. Aenean sed augue et ex sollicitudin vestibulum. Ut facilisis mollis urna in placerat. Vestibulum eu nisi non nunc sollicitudin posuere venenatis id justo. Donec lobortis ornare varius. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam venenatis sit amet ante at varius.

Etiam faucibus euismod neque. Duis ac venenatis nulla, et efficitur dui. Donec quis tincidunt metus, id pellentesque erat. Cras non venenatis justo. Mauris vestibulum, tellus nec dignissim rutrum, nulla sem ornare tortor, id placerat arcu enim sit amet erat. Quisque maximus in enim ac tristique. Vestibulum aliquet nisl non sapien iaculis, tempus sodales arcu tincidunt. Maecenas efficitur in metus aliquam cursus. Donec at mi lobortis, scelerisque lectus eget, cursus metus. Aliquam faucibus laoreet risus quis vehicula. Donec laoreet varius metus, vitae pharetra lectus eleifend sit amet. Vestibulum scelerisque vel diam et ultrices. Nam vel erat molestie, cursus orci nec, placerat leo. Sed semper vel arcu congue convallis. Donec nec velit aliquam, semper justo sed, feugiat odio. In viverra enim sit amet ligula cursus vestibulum.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur sagittis dapibus turpis, sit amet venenatis leo mattis id. Sed sed est ac eros tincidunt ultricies sit amet a arcu. Proin suscipit lacus odio, ac bibendum orci mattis id. Nullam est ante, egestas eu volutpat eu, consectetur at felis. Donec a urna tincidunt, tempus erat vitae, sodales magna. Suspendisse tincidunt elit molestie massa bibendum, suscipit tempor dolor finibus. Cras vel lorem pellentesque, sagittis justo semper, fringilla quam. Ut vel ante eu mi sollicitudin eleifend at non magna.''';
